# Generated by Django 4.1.3 on 2022-11-13 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0004_meals_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "category", "verbose_name_plural": "categories"},
        ),
    ]
