# Generated by Django 4.1.3 on 2022-11-17 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aboutus", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Why_Choose", new_name="Why_Choose_Us",),
    ]
