# Generated by Django 4.1.3 on 2022-11-17 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aboutus", "0002_rename_why_choose_why_choose_us"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutus",
            options={"verbose_name": "about us", "verbose_name_plural": "about us"},
        ),
        migrations.AlterModelOptions(
            name="chef",
            options={"verbose_name": "chef", "verbose_name_plural": "chef"},
        ),
        migrations.AlterModelOptions(
            name="why_choose_us",
            options={
                "verbose_name": "why choose us",
                "verbose_name_plural": "why choose us",
            },
        ),
        migrations.RemoveField(model_name="aboutus", name="image",),
    ]
